// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebDay2.Models;

#nullable disable

namespace WebDay2.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240219160647_ClassRoomEF")]
    partial class ClassRoomEF
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.2");

            modelBuilder.Entity("WebDay2.Models.ClassRoom", b =>
                {
                    b.Property<int>("ClassRoomID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.HasKey("ClassRoomID");

                    b.ToTable("ClassRoom");
                });

            modelBuilder.Entity("WebDay2.Models.Student", b =>
                {
                    b.Property<int>("StudentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DOB")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("MyClassRoomClassRoomID")
                        .HasColumnType("INTEGER");

                    b.HasKey("StudentID");

                    b.HasIndex("MyClassRoomClassRoomID");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("WebDay2.Models.Student", b =>
                {
                    b.HasOne("WebDay2.Models.ClassRoom", "MyClassRoom")
                        .WithMany("Students")
                        .HasForeignKey("MyClassRoomClassRoomID");

                    b.Navigation("MyClassRoom");
                });

            modelBuilder.Entity("WebDay2.Models.ClassRoom", b =>
                {
                    b.Navigation("Students");
                });
#pragma warning restore 612, 618
        }
    }
}
